# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFrm.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainFrmDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1960, 1080)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(60, 40, 1071, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber.setGeometry(QtCore.QRect(750, 90, 121, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(360, 90, 261, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 251, 461))
        self.groupBox.setObjectName("groupBox")
        self.label_sat_id = QtWidgets.QLabel(self.groupBox)
        self.label_sat_id.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_sat_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sat_id.setObjectName("label_sat_id")
        self.lE_sat_id = QtWidgets.QLineEdit(self.groupBox)
        self.lE_sat_id.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lE_sat_id.setReadOnly(True)
        self.lE_sat_id.setObjectName("lE_sat_id")
        self.lE_reboot_cnt = QtWidgets.QLineEdit(self.groupBox)
        self.lE_reboot_cnt.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lE_reboot_cnt.setReadOnly(True)
        self.lE_reboot_cnt.setObjectName("lE_reboot_cnt")
        self.lE_rec_cmd_cnt = QtWidgets.QLineEdit(self.groupBox)
        self.lE_rec_cmd_cnt.setGeometry(QtCore.QRect(120, 130, 111, 31))
        self.lE_rec_cmd_cnt.setReadOnly(True)
        self.lE_rec_cmd_cnt.setObjectName("lE_rec_cmd_cnt")
        self.lE_obc_utc_tiime = QtWidgets.QLineEdit(self.groupBox)
        self.lE_obc_utc_tiime.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lE_obc_utc_tiime.setReadOnly(True)
        self.lE_obc_utc_tiime.setObjectName("lE_obc_utc_tiime")
        self.lE_down_cnt = QtWidgets.QLineEdit(self.groupBox)
        self.lE_down_cnt.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lE_down_cnt.setReadOnly(True)
        self.lE_down_cnt.setObjectName("lE_down_cnt")
        self.lE_reboot_time = QtWidgets.QLineEdit(self.groupBox)
        self.lE_reboot_time.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lE_reboot_time.setReadOnly(True)
        self.lE_reboot_time.setObjectName("lE_reboot_time")
        self.label_reboot_cnt = QtWidgets.QLabel(self.groupBox)
        self.label_reboot_cnt.setGeometry(QtCore.QRect(20, 100, 72, 15))
        self.label_reboot_cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reboot_cnt.setObjectName("label_reboot_cnt")
        self.label_rec_cmd_cnt = QtWidgets.QLabel(self.groupBox)
        self.label_rec_cmd_cnt.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_rec_cmd_cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rec_cmd_cnt.setObjectName("label_rec_cmd_cnt")
        self.label_down_cnt = QtWidgets.QLabel(self.groupBox)
        self.label_down_cnt.setGeometry(QtCore.QRect(20, 180, 72, 15))
        self.label_down_cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_down_cnt.setObjectName("label_down_cnt")
        self.label_reboot_time = QtWidgets.QLabel(self.groupBox)
        self.label_reboot_time.setGeometry(QtCore.QRect(20, 220, 72, 15))
        self.label_reboot_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reboot_time.setObjectName("label_reboot_time")
        self.label_obc_utc_time = QtWidgets.QLabel(self.groupBox)
        self.label_obc_utc_time.setGeometry(QtCore.QRect(20, 260, 72, 15))
        self.label_obc_utc_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_obc_utc_time.setObjectName("label_obc_utc_time")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 30, 241, 461))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lE_BusC = QtWidgets.QLineEdit(self.groupBox_3)
        self.lE_BusC.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lE_BusC.setReadOnly(True)
        self.lE_BusC.setObjectName("lE_BusC")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_15.setObjectName("label_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_BusV = QtWidgets.QLabel(self.groupBox_3)
        self.label_BusV.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_BusV.setObjectName("label_BusV")
        self.label_BusC = QtWidgets.QLabel(self.groupBox_3)
        self.label_BusC.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_BusC.setObjectName("label_BusC")
        self.lE_BusV = QtWidgets.QLineEdit(self.groupBox_3)
        self.lE_BusV.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lE_BusV.setReadOnly(True)
        self.lE_BusV.setObjectName("lE_BusV")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(800, 40, 241, 461))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_20.setObjectName("label_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_21.setObjectName("label_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_23.setObjectName("label_23")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_23.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(530, 40, 241, 461))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_45 = QtWidgets.QLabel(self.groupBox_13)
        self.label_45.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_13)
        self.label_46.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_13)
        self.label_47.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_47.setObjectName("label_47")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_44.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_45.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_46.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_47.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lineEdit_47.setReadOnly(True)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_13)
        self.label_48.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_48.setObjectName("label_48")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_48.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lineEdit_48.setReadOnly(True)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_13)
        self.label_49.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_13)
        self.label_50.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_50.setObjectName("label_50")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_49.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(550, 30, 241, 461))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_26.setObjectName("label_26")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_24.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_25.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_26.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_27.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_27.setObjectName("label_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_28.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_29.setObjectName("label_29")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_29.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 30, 241, 461))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_adcs_reboot_cnt = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_reboot_cnt.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_adcs_reboot_cnt.setObjectName("label_adcs_reboot_cnt")
        self.label_adcs_rec_cnt = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_rec_cnt.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_adcs_rec_cnt.setObjectName("label_adcs_rec_cnt")
        self.label_adcs_send_cnt = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_send_cnt.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_adcs_send_cnt.setObjectName("label_adcs_send_cnt")
        self.lE_adcs_reboot_cnt = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_reboot_cnt.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lE_adcs_reboot_cnt.setReadOnly(True)
        self.lE_adcs_reboot_cnt.setObjectName("lE_adcs_reboot_cnt")
        self.lE_adcs_rec_cnt = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_rec_cnt.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lE_adcs_rec_cnt.setReadOnly(True)
        self.lE_adcs_rec_cnt.setObjectName("lE_adcs_rec_cnt")
        self.lE_adcs_send_cnt = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_send_cnt.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lE_adcs_send_cnt.setReadOnly(True)
        self.lE_adcs_send_cnt.setObjectName("lE_adcs_send_cnt")
        self.lE_adcs_mode = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_mode.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lE_adcs_mode.setReadOnly(True)
        self.lE_adcs_mode.setObjectName("lE_adcs_mode")
        self.label_adcs_reboot_time = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_reboot_time.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_adcs_reboot_time.setObjectName("label_adcs_reboot_time")
        self.lE_adcs_reboot_time = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_reboot_time.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lE_adcs_reboot_time.setReadOnly(True)
        self.lE_adcs_reboot_time.setObjectName("lE_adcs_reboot_time")
        self.label_adcs_utc_time = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_utc_time.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_adcs_utc_time.setObjectName("label_adcs_utc_time")
        self.label_adcs_mode = QtWidgets.QLabel(self.groupBox_6)
        self.label_adcs_mode.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_adcs_mode.setObjectName("label_adcs_mode")
        self.lE_adcs_utc_time = QtWidgets.QLineEdit(self.groupBox_6)
        self.lE_adcs_utc_time.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lE_adcs_utc_time.setReadOnly(True)
        self.lE_adcs_utc_time.setObjectName("lE_adcs_utc_time")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(280, 30, 241, 461))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        self.label_36.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        self.label_38.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_38.setObjectName("label_38")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_36.setGeometry(QtCore.QRect(100, 50, 111, 31))
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_37.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_38.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_39.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setGeometry(QtCore.QRect(20, 170, 72, 15))
        self.label_39.setObjectName("label_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_40.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(20, 250, 72, 15))
        self.label_41.setObjectName("label_41")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_41.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pBtn_test = QtWidgets.QPushButton(self.tab_6)
        self.pBtn_test.setGeometry(QtCore.QRect(700, 400, 93, 28))
        self.pBtn_test.setObjectName("pBtn_test")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 40, 371, 201))
        self.groupBox_8.setObjectName("groupBox_8")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 60, 121, 41))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox.setGeometry(QtCore.QRect(30, 30, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_9.setGeometry(QtCore.QRect(410, 40, 381, 201))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 111, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit.setGeometry(QtCore.QRect(150, 40, 141, 31))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(40, 50, 431, 231))
        self.groupBox_10.setObjectName("groupBox_10")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox.setGeometry(QtCore.QRect(140, 20, 221, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_port = QtWidgets.QLabel(self.groupBox_10)
        self.label_port.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label_port.setObjectName("label_port")
        self.label_up_port = QtWidgets.QLabel(self.groupBox_10)
        self.label_up_port.setGeometry(QtCore.QRect(30, 70, 72, 15))
        self.label_up_port.setObjectName("label_up_port")
        self.label_down_port = QtWidgets.QLabel(self.groupBox_10)
        self.label_down_port.setGeometry(QtCore.QRect(30, 110, 72, 15))
        self.label_down_port.setObjectName("label_down_port")
        self.lE_up_port = QtWidgets.QLineEdit(self.groupBox_10)
        self.lE_up_port.setGeometry(QtCore.QRect(140, 60, 221, 31))
        self.lE_up_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lE_up_port.setObjectName("lE_up_port")
        self.lE_down_port = QtWidgets.QLineEdit(self.groupBox_10)
        self.lE_down_port.setGeometry(QtCore.QRect(140, 100, 221, 31))
        self.lE_down_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lE_down_port.setObjectName("lE_down_port")
        self.pBtn_open_conn = QtWidgets.QPushButton(self.groupBox_10)
        self.pBtn_open_conn.setGeometry(QtCore.QRect(60, 170, 291, 41))
        self.pBtn_open_conn.setObjectName("pBtn_open_conn")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_4)
        self.calendarWidget.setGeometry(QtCore.QRect(570, 20, 296, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_11.setGeometry(QtCore.QRect(50, 300, 411, 201))
        self.groupBox_11.setObjectName("groupBox_11")
        self.tE_rec_buff = QtWidgets.QTextEdit(self.groupBox_11)
        self.tE_rec_buff.setGeometry(QtCore.QRect(10, 30, 381, 151))
        self.tE_rec_buff.setObjectName("tE_rec_buff")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_12.setGeometry(QtCore.QRect(500, 290, 441, 211))
        self.groupBox_12.setObjectName("groupBox_12")
        self.tE_send_buff = QtWidgets.QTextEdit(self.groupBox_12)
        self.tE_send_buff.setGeometry(QtCore.QRect(20, 40, 401, 151))
        self.tE_send_buff.setObjectName("tE_send_buff")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "首页"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "卫星状态"))
        self.groupBox.setTitle(_translate("Dialog", "星务信息"))
        self.label_sat_id.setText(_translate("Dialog", "ID"))
        self.label_reboot_cnt.setText(_translate("Dialog", "重启计数"))
        self.label_rec_cmd_cnt.setText(_translate("Dialog", "接收指令计数"))
        self.label_down_cnt.setText(_translate("Dialog", "下行计数"))
        self.label_reboot_time.setText(_translate("Dialog", "复位时间"))
        self.label_obc_utc_time.setText(_translate("Dialog", "星上时间"))
        self.groupBox_3.setTitle(_translate("Dialog", "电源"))
        self.label_12.setText(_translate("Dialog", "TextLabel"))
        self.label_13.setText(_translate("Dialog", "TextLabel"))
        self.label_14.setText(_translate("Dialog", "TextLabel"))
        self.label_15.setText(_translate("Dialog", "TextLabel"))
        self.label_BusV.setText(_translate("Dialog", "母线电压"))
        self.label_BusC.setText(_translate("Dialog", "母线电流"))
        self.groupBox_4.setTitle(_translate("Dialog", "通信"))
        self.label_18.setText(_translate("Dialog", "TextLabel"))
        self.label_19.setText(_translate("Dialog", "TextLabel"))
        self.label_20.setText(_translate("Dialog", "TextLabel"))
        self.label_21.setText(_translate("Dialog", "TextLabel"))
        self.label_22.setText(_translate("Dialog", "TextLabel"))
        self.label_23.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_13.setTitle(_translate("Dialog", "温度"))
        self.label_45.setText(_translate("Dialog", "TextLabel"))
        self.label_46.setText(_translate("Dialog", "TextLabel"))
        self.label_47.setText(_translate("Dialog", "TextLabel"))
        self.label_48.setText(_translate("Dialog", "TextLabel"))
        self.label_49.setText(_translate("Dialog", "TextLabel"))
        self.label_50.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "星务信息"))
        self.groupBox_5.setTitle(_translate("Dialog", "GroupBox"))
        self.label_24.setText(_translate("Dialog", "TextLabel"))
        self.label_25.setText(_translate("Dialog", "TextLabel"))
        self.label_26.setText(_translate("Dialog", "TextLabel"))
        self.label_27.setText(_translate("Dialog", "TextLabel"))
        self.label_28.setText(_translate("Dialog", "TextLabel"))
        self.label_29.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_6.setTitle(_translate("Dialog", "姿控状态"))
        self.label_adcs_reboot_cnt.setText(_translate("Dialog", "重启计数"))
        self.label_adcs_rec_cnt.setText(_translate("Dialog", "接收指令计数"))
        self.label_adcs_send_cnt.setText(_translate("Dialog", "发送计数"))
        self.label_adcs_reboot_time.setText(_translate("Dialog", "复位时间"))
        self.label_adcs_utc_time.setText(_translate("Dialog", "UTC时间"))
        self.label_adcs_mode.setText(_translate("Dialog", "姿控模式"))
        self.groupBox_7.setTitle(_translate("Dialog", "GroupBox"))
        self.label_36.setText(_translate("Dialog", "TextLabel"))
        self.label_37.setText(_translate("Dialog", "TextLabel"))
        self.label_38.setText(_translate("Dialog", "TextLabel"))
        self.label_39.setText(_translate("Dialog", "TextLabel"))
        self.label_40.setText(_translate("Dialog", "TextLabel"))
        self.label_41.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "姿控信息"))
        self.pBtn_test.setText(_translate("Dialog", "测试"))
        self.groupBox_8.setTitle(_translate("Dialog", "GroupBox"))
        self.checkBox_3.setText(_translate("Dialog", "CheckBox"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.groupBox_9.setTitle(_translate("Dialog", "GroupBox"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "控制指令"))
        self.groupBox_10.setTitle(_translate("Dialog", "GroupBox"))
        self.label_port.setText(_translate("Dialog", "端口"))
        self.label_up_port.setText(_translate("Dialog", "上行端口"))
        self.label_down_port.setText(_translate("Dialog", "下行端口"))
        self.lE_up_port.setText(_translate("Dialog", "60061"))
        self.lE_down_port.setText(_translate("Dialog", "60060"))
        self.pBtn_open_conn.setText(_translate("Dialog", "打开端口"))
        self.groupBox_11.setTitle(_translate("Dialog", "接收缓冲区"))
        self.groupBox_12.setTitle(_translate("Dialog", "发送缓冲区"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "监控设置"))

